# curl -X post http://localhost/shutdown  return  "message": "Shutting down, bye..."
endpoints:
  shutdown:
    enabled: true
    sensitive: false

management:
  security:
    enabled: false #actuator rest 不用鉴权