
spring:
     datasource:
              url: jdbc:mysql://127.0.0.1:3306/test?autoReconnect=true&useCompression=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
              username: root
              password: root
     jpa:
       show-sql: false

logging:
  level:
      org.hibernate: warn
