jwt:
  header: Authorization
  secret: selectData
  expiration: 604800
  route:
    authentication:
      init: init
      path: auth
      refresh: refresh

spring:
     datasource:
              url: jdbc:mysql://127.0.0.1:3306/test?autoReconnect=true&useCompression=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
              username: root
              password: root
     jpa:
       show-sql: true
logging:
  file: logs/selectdata.log
  level:
      root: info
      org.hibernate: debug


